# This is necessary due to the way the Ansible setup process inherits
# variables from the play.  The system path is prepended with /usr/local/bin
# below to ensure the system on which the playbook is run selects the correct
# copy of zsh, etc.  In other words, to make sure it uses /usr/local/bin/zsh
# installed with Homebrew and not the older macOS /bin/zsh.
- hosts: localhost
  tasks:
    - command: echo "$PATH"
      register: system_path

- hosts: localhost
  environment:
    PATH: "/usr/local/bin:{{ system_path.stdout }}"

  tasks:
    # essentials:
    - include_tasks: tasks/homebrew.yml
    - include_tasks: tasks/fonts.yml
    - include_tasks: tasks/directories.yml
    - include_tasks: tasks/core.yml
    - include_tasks: tasks/diff.yml
    - include_tasks: tasks/dotfiles.yml
    - include_tasks: tasks/zsh.yml
    - include_tasks: tasks/terminal.yml
    - include_tasks: tasks/crypto.yml

    # common applications:
    #- include_tasks: tasks/alfred.yml
    - include_tasks: tasks/chrome.yml
    #- include_tasks: tasks/dropbox.yml
    - include_tasks: tasks/slack.yml
    - include_tasks: tasks/omnifocus.yml
    - include_tasks: tasks/evernote.yml
    - include_tasks: tasks/kindle.yml

    # development-related:
    - include_tasks: tasks/nodejs.yml
    - include_tasks: tasks/atom.yml
    - include_tasks: tasks/docker.yml
    - include_tasks: tasks/anaconda.yml
    - include_tasks: tasks/virtualbox.yml
    - include_tasks: tasks/vagrant.yml
    - include_tasks: tasks/terraform.yml

    # microsoft-related:
    - include_tasks: tasks/powershell.yml
    - include_tasks: tasks/visual-studio-code.yml
    - include_tasks: tasks/remote-desktop.yml

    # OMSCS program:
    - include_tasks: tasks/pycharm.yml
    - include_tasks: tasks/latex.yml
