- name: Install Microsoft .NET Core
  homebrew_cask: name=dotnet

- name: Install Microsoft PowerShell
  homebrew_cask: name=powershell

- name: Install Rollup Module for ARM Cmdlets
  command: pwsh -c "{Install-Module AzureRM}"

- name: Import Rollup Module for ARM Cmdlets
  command: pwsh -c "{Import-Module AzureRM}"

- name: Install Rollup Module for .NET Core Cmdlets
  command: pwsh -c "{Install-Module AzureRM.NetCore}"

- name: Import Rollup Module for .NET Core Cmdlets
  command: pwsh -c "{Import-Module AzureRM.NetCore}"
